### ISSUE TITLE
Not able to start practice

### ISSUE THREAD

**Issue by lluni** [kcapp/frontend#135]
When opening the practice page it looks like this:
![image](https://user-images.githubusercontent.com/36239317/211021938-7593aaf6-b3e0-4630-bea3-67ef5c51e914.png)
I don't know whether (1.) should have some text, but it is empty with no selectable option and (2.) only has the option for 301.

After selecting a player and a mock player (or bot difficulty, it doesn't matter) and trying to start, the console spits out an error and I stay on the same page:
```
Uncaught TypeError: s is undefined
    newGame http://192.168.178.96:3000/static/pages-f36ac701.js:208
    l http://192.168.178.96:3000/static/pages-f36ac701.js:29
    n http://192.168.178.96:3000/static/pages-f36ac701.js:29
```

I'm using the following docker compose setup:

.env
```
KCAPP_API="http://api:8001"
KCAPP_API_VERSION="latest"
KCAPP_FRONTEND_VERSION="latest"
MYSQL_DATABASE="kcapp"
MYSQL_USER="kcapp"
MYSQL_PASSWORD="abcd1234"
MYSQL_ROOT_PASSWORD="kcapp"
MYSQL_LISTEN_ADDR="0.0.0.0"
API_LISTEN_ADDR="0.0.0.0"
KCAPP_FRONTEND_LISTEN_ADDR="0.0.0.0"
MYSQL_LISTEN_PORT=3306
API_LISTEN_PORT=8001
KCAPP_FRONTEND_LISTEN_PORT=3000
NODE_ENV="prod"
DISK_CACHE="true"
```

docker-compose.yaml
```YAML
version: '3.6'
services:
  db:
    image: linuxserver/mariadb:110.4.12mariabionic-ls59
    #command: mysqld --sql_mode=""
    restart: always
    volumes:
      - db_config:/config
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - kcapp
  migration:
    image: kcapp/api:$KCAPP_API_VERSION
    command: [ "./wait-for-it.sh", "db:3306", "--", "./run_migrations.sh" ]
    depends_on:
      - db
    environment:
      DB_CONNECTION: "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(db:3306)/${MYSQL_DATABASE}?parseTime=true"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - kcapp
  api:
    image: kcapp/api:$KCAPP_API_VERSION
    restart: always
    ports:
      - "${API_LISTEN_PORT}:8001"
    expose:
      - ${API_LISTEN_PORT}
    depends_on:
      - migration
      - db
    command: [ "./wait-for-it.sh", "db:3306", "--", "/go/bin/api" ]
    networks:
      - kcapp
  frontend:
    image: kcapp/frontend:$KCAPP_FRONTEND_VERSION
    restart: always
    ports:
      - "${KCAPP_FRONTEND_LISTEN_PORT}:3000"
    expose:
      - ${KCAPP_FRONTEND_LISTEN_PORT}
    volumes:
      - frontend_cache:/.cache
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - api
    environment:
      - DEBUG=kcapp:*,kcapp-bot:*
      - KCAPP_API
      - DISK_CACHE
      - NODE_ENV
    networks:
      - kcapp
    privileged: true
volumes:
  db:
  db_config:
  frontend_cache:
networks:
  kcapp:
    name: kcapp

```
(The `privileged: true` is only there because node.js has (or had?) a bug where it crashes on ARM devices if it is run as a unprivileged container.)
